# docker-compose.yml
version: '3.8'

services:
  test_db:
    image: postgres:13
    container_name: mi_app_test_db
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    ports:
      - "54321:5432" 
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: