# Nombre de este workflow de diagnóstico
name: Diagnóstico de Checkout

# Se ejecuta en cada push para que podamos probarlo fácilmente
on: [push]

jobs:
  # Un único trabajo
  test-checkout:
    # Corre en la máquina virtual estándar
    runs-on: ubuntu-latest
    steps:
      # El único paso: intentar descargar el código
      - name: Intentando ejecutar actions/checkout@v4
        uses: actions/checkout@v4
      
      # Si la línea anterior funciona, este paso se ejecutará
      - name: ¡Éxito!
        run: echo "La acción checkout funcionó sin problemas."

